### ISSUE TITLE
Very odd behaviour compared to a week ago

### ISSUE THREAD

**Issue by Xirious** [seanlennaerts/mcuverse#14]
Some search results are not returning the same for me compared to a week ago when the tool was first put on Reddit. 

1 - Previous version had Thor's "anus" comments in (I test it back then and [here are examples of this here](https://www.reddit.com/r/marvelstudios/comments/c0sbxv/now_you_can_quote_thanos_like_its_a_bible_verse/er7il8t/)

2 - Now I get the following when searching for "anus":

https://i.imgur.com/QW30WiR.png

This clearly does not contain two examples given by the comment: 

Anus? (III Thor 1:25:39)
Wait, wait, wait. Whose anus? (III Thor 1:25:41)

Could you advise as to why this is happening?

**Comment by JakubKoralewski** [comment]
Looks like someone did a search and replace lol.
