### ISSUE TITLE
Set-up Netlify to build and preview PRs instead of gh-pages

### ISSUE THREAD

**Issue by JakubKoralewski** [seanlennaerts/mcuverse#18]
In addition I'd also move from gh-pages to netlify for the master. 

The github.io domain can stay with some additional config: https://help.github.com/en/articles/using-a-custom-domain-with-github-pages

**Comment by seanlennaerts** [comment]
this looks really cool, looking into it thanks

**Comment by seanlennaerts** [comment]
Done! Thanks for the suggestions.
