### ISSUE TITLE
Allow linking to MCU verses

### ISSUE THREAD

**Issue by ocdtrekkie** [seanlennaerts/mcuverse#20]
It'd be nice if we could create a link which linked you back to the MCU Bible Verse page for a given verse. I wanted to highlight this project when someone referenced a line, but I had to both provide the reference (III Avengers, etc.) and then when someone asked where I got that, provide the link to the page (but not the quote on the page).

I'd love to get a link like https://seanlennaerts.github.io/mcuverse/3Avengers143:04 or something similar.

**Comment by seanlennaerts** [comment]
If you click on the reddit share icon it will copy the quote with a link to the quote formatted with reddit's markdown ready to paste!

**Comment by ocdtrekkie** [comment]
Ah, thanks! This was non-obvious, but I'm glad I can do it!
