### ISSUE TITLE
You should remove the images from version control

### ISSUE THREAD

**Issue by JakubKoralewski** [seanlennaerts/mcuverse#22]
I don't think it's a good idea to have to clone a 2gb repo if someone would want to contribute a small change. If you could put them somewhere else and let people download them only if they wanted it that would be great. 

I'm not sure how git submodules work, but if it's possible you could put the images in another git repository and then link to it in this repo. If I remember correctly you have to pull the submodules explicitly, so the images wouldn't be there until you pulled that submodule, but I'm not sure.

**Comment by seanlennaerts** [comment]
just opened #23 before I saw this. Will fix that over the weekend, thanks!
